label RETROPANGUI-C5
    kernel /Image
    fdt /s7d_s905x5m_odroidc5.dtb
    append console=tty1 console=ttyS0,115200n8 earlycon=aml_uart,0xfe07a000 root=/dev/mmcblk1p2 rootwait rw fsck.repair=yes net.ifnames=0 clk_ignore_unused vout=1920x1080p60hz,enable connector0_type=HDMI-A-A hdmimode=1920x1080p60hz hdmitx=,422,12bit
