[global]
	server string = RETROPANGUI-C5 Retro Gaming
	netbios name = RETROPANGUI-C5
	workgroup = WORKGROUP
	server signing = auto
	server min protocol = SMB2_02
	guest ok = no

[SHARE]
	path = /retropangui/share
	comment = RETROPANGUI-C5 ROM Share
	writable = yes
	valid users = pangui
	force user = root
